### ISSUE TITLE
add transaction group query parameters

### ISSUE THREAD

**Issue by jeapostrophe** [algorand/indexer#211] opened 2020-10-01 01:44 UTC
In particular, I want to be able to specify the groupId and the position of a transaction within a group

**Comment by brianolson** [comment] 2020-10-01 11:08
see #135

**Comment by jeapostrophe** [comment] 2020-10-01 13:36
I'll comment over there

**Comment by winder** [comment] 2020-10-15 18:25
Duplicate of #135

**Closed by winder** 2020-10-15 18:25 UTC
Labels: FDE, duplicate
