### ISSUE TITLE
Duplicate close-amount/closing-amount field 

### ISSUE THREAD

**Issue by barnjamin** [algorand/indexer#971] opened 2022-04-22 10:46 UTC
A community member (Frank) noticed that the closing amount field in the transaction payload 

https://github.com/algorand/indexer/blob/99ab66fdadcd77fef4048bb2aa86cae1f06c6e08/api/converter_utils.go#L311

https://github.com/algorand/indexer/blob/99ab66fdadcd77fef4048bb2aa86cae1f06c6e08/api/converter_utils.go#L489

Are both of these necessary?

**Comment by Eric-Warehime** [comment] 2022-05-09 17:09
I looked into this a bit, but we need some more investigation...

The closing amount is indeed duplicated in this API response. The cause of this is that the `Transaction` type in our API definition has a [closing amount](https://github.com/algorand/indexer/blob/99ab66fdadcd77fef4048bb2aa86cae1f06c6e08/api/indexer.oas2.json#L1797) and potentially a [payment transaction](https://github.com/algorand/indexer/blob/99ab66fdadcd77fef4048bb2aa86cae1f06c6e08/api/indexer.oas2.json#L1860) (which has a closing amount in it).

I think the fact that the txn might not have a payment txn means it's not a duplicated field 100% of the time, and I don't really see a reason to remove the closing amount from the PaymentTransaction type either.

Like I said, I just took a brief look at this so maybe there is a way we can separate these and remove one that's not immediately obvious.

**Comment by FrankSzendzielarz** [comment] 2022-05-16 11:08
> "I think the fact that the txn might not have a payment txn "

I think the issue there is that the json spec is trying to model inheritance via composition. A transaction does not 'have' a payment transaction - it either 'is' a payment transaction or is not.

**Closed** 2024-08-09 19:12 UTC
Labels: new-bug, Team Lamprey
