### ISSUE TITLE
transaction response come back with two similar fields 

### ISSUE THREAD

**Issue by algorotem** [algorand/indexer#163] opened 2020-07-30 14:50 UTC
For example 
https://indexer-mainnet.aws.algodev.network/v2/transactions?txid=IWKY4XBCAJGZIIYJOJKTQ2SLY6DH27QL72ZHSOKMHIBHFVN5YDPQ

returns `close-rewards` and `closing-rewards` is that the same field?

**Comment by winder** [comment] 2021-02-05 19:36
this is probably a bug and we'll need to fix close-amount / deprecate closing-amount

**Comment by winder** [comment] 2022-04-25 17:27
Related to #971

**Comment by chaihoang** [comment] 2022-08-04 14:35
Duplicate of #971

**Closed by chaihoang** 2022-08-04 14:35 UTC
Labels: bug, Team Lamprey
