### ISSUE TITLE
Error when fetching range of accounts from indexer REST API.

### ISSUE THREAD

**Issue by egieseke** [algorand/indexer#306] opened 2021-02-06 14:30 UTC
## Summary
Indexer consistently fails to return a  range of accounts with this request:

`192.168.22.66 - - [04/Feb/2021:06:44:50 +0000] "GET /v2/accounts?limit=500&next=SCKF4Q6OJCN4RIREPXLWHJ2JRI5WXMNKOV5ADOPNJSVI2QXLEUGZTPUSIA HTTP/1.1" 500 121 "-" "python-urllib3/1.26.2" 295 0.023 [testnet-testnet-indexer-reader-8980] [] 192.168.104.188:8980 121 0.020 500 604f7b8c987b5a0a15b53c31b7806856`

The indexer-db-validator script terminated at this point.
All previous queries were successful.  

## Scope/Requirements
Run the above query using the testnet environment. 

## Urgency/Relative Priority
High:

## DataDog issue report:

More than 0.0 log events matched in the last 15m against the monitored query: \@proxy.name:testnet-testnet-indexer-reader-8980 service:nginx-ingress-controller \@http.status_code:[500 TO 599]

The monitor was last triggered at Thu Feb 04 2021 06:46:50 UTC.

[Monitor Status] · [Edit Monitor] · [Related Logs]

This alert was raised by account Algorand

Sample Logs:

```
Time	Host
06:44:50 UTC	i-0003154418ac72c16
192.168.22.66 - - [04/Feb/2021:06:44:50 +0000] "GET /v2/accounts?limit=500&next=SCKF4Q6OJCN4RIREPXLWHJ2JRI5WXMNKOV5ADOPNJSVI2QXLEUGZTPUSIA HTTP/1.1" 500 121 "-" "python-urllib3/1.26.2" 295 0.023 [testnet-testnet-indexer-reader-8980] [] 192.168.104.188:8980 121 0.020 500 604f7b8c987b5a0a15b53c31b7806856
```

**Comment by winder** [comment] 2021-02-06 14:44
Could you share the curl command and response from indexer? What is the error message? Has this server been configured with the longer timeout used by some of our other indexer deployments?

You can try reducing the limit to narrow down which account is causing the slowness.

**Comment by egieseke** [comment] 2021-02-06 14:52
ERROR:__main__:bad response to 'https://indexer-testnet.aws.algodev.network/v2/accounts?limit=500&next=SCKDTKDGYNPHP6M4QMKOB36J3TWLSIPQHTFEWP7AZLS3DU5NWUF4CS4ECU': Internal Server Error

The indexer-db-validator script consistently fails when fetching this account page.    I added retries,  which does not help.

curl -H "x-indexer-api-token:KegWFLYQnBNVeP4oHCX64dObBk8VemzYdNqsnAOIxYQ8aqJLQTYeVDQyZNnx1PZA" https://indexer-testnet.aws.algodev.network/v2/accounts?limit=500
new-host-2:loadgenerator ericgieseke$ curl -H "x-indexer-api-token:api-token" https://indexer-testnet.aws.algodev.network/v2/accounts?limit=500&next=SCKF4Q6OJCN4RIREPXLWHJ2JRI5WXMNKOV5ADOPNJSVI2QXLEUGZTPUSIA

**Comment by egieseke** [comment] 2021-02-06 20:48
Attached is the full log from the run with using testnet.  It. was generated with the following command.

python3 \
    "${SCRIPT_PATH}/validate_accounting.py" \
    --genesis "${SCRIPT_PATH}/algod-data/genesis.json" \
    --indexer "https://indexer-testnet.aws.algodev.network" \
    --indexer-token "indexer token" \
    --algod-net "https://node-testnet.aws.algodev.network:443" \
    --algod-token "algo api token"


[indexer-db-validator-testnet-02_06_2021.log](https://github.com/algorand/indexer/files/5937633/indexer-db-validator-testnet-02_06_2021.log)

**Comment by onetechnical** [comment] 2021-02-09 18:47
`ERROR:__main__:bad response to 'https://indexer-testnet.aws.algodev.network/v2/accounts?limit=500&next=SCKDTKDGYNPHP6M4QMKOB36J3TWLSIPQHTFEWP7AZLS3DU5NWUF4CS4ECU': Internal Server Error
`
The indexer-db-validator script consistently fails when fetching this account page.    I added retries,  which does not help.

```
curl -H "x-indexer-api-token:REDACTED" https://indexer-testnet.aws.algodev.network/v2/accounts?limit=500
new-host-2:loadgenerator ericgieseke$ curl -H "x-indexer-api-token:api-token" https://indexer-testnet.aws.algodev.network/v2/accounts?limit=500&next=SCKF4Q6OJCN4RIREPXLWHJ2JRI5WXMNKOV5ADOPNJSVI2QXLEUGZTPUSIA

```
the individual curl command works, but the request fails when paging through the accounts

**Comment by winder** [comment] 2021-02-13 00:45
@egieseke is this still an issue? If yes could you share the error message returned with the 500 code? I have seen 500s come from nginx in our indexer deployments so there isn't enough information here to investigate anything.

**Comment by egieseke** [comment] 2021-02-13 02:47
@winder To reproduce, rapidly page through the accounts. I believe that @brianolson also saw it.  This is the log message recorded on the server:  {"level":"info","msg":"192.168.26.56:41090 - - [2021-02-09 20:52:36.799326145 +0000 UTC m=+340016.407250636] \"GET /v2/accounts?limit=500\u0026next=YDVBMOMTI3LZ7BCWDHQ6CD3Z4WASEJDQKWKGS5ZACYNEPXUUTAQDCSAATQ HTTP/1.1\" 500 183 \"python-urllib3/1.26.2\" 24.563568ms","time":"2021-02-09T20:52:36Z"}

**Comment by brianolson** [comment] 2021-02-16 13:02
I haven't seen anything like this is several runs of validate_accounting.py on mainnet

**Comment by egieseke** [comment] 2021-02-16 13:40
I haven't seen it since the validate_accounting.py script was updated, but I wonder if it is reproducible with the old version of the script.

**Comment by winder** [comment] 2021-02-17 14:22
@egieseke that a log message, not the body of the 500 response with error details. Since this isn't reproducible I'll go ahead and close the issue.

**Closed by winder** 2021-02-17 14:22 UTC
Labels: bug
