### ISSUE TITLE
Indexer triggers DB error "FATAL:  sorry, too many clients already" when doing too many sequential queries (no parallel queries)

### ISSUE THREAD

**Issue by fabrice102** [algorand/indexer#553] opened 2021-06-28 02:15 UTC
## Summary

Querying accounts with a previous round *even sequentially* make the DB display the following error:
```plain
FATAL:  sorry, too many clients already
```
and then a long list of
```plain
LOG:  unexpected EOF on client connection with an open transaction
```

The indexer returns the message:
```plain
{"message":"Indexer health error: %s"}
```
(error 500)
and sometimes completely crashes.

To try, run:
```bash
for i in $(seq 200)
do
  curl "$AF_IDX_ADDRESS/v2/accounts/GFIDQ2XIX2CMPJZ4DS3ISIOPOCJQDGRB5JQGCVHG63CACQF3OXXRBLOIDM?round=15049487"
done
```
against an indexer `$AF_IDX_ADDRESS` for TestNet.
(You may want to change the round to the current round.)

Note that this code does not make any parallel queries to the indexer, it waits for the previous query to end before making a new query. So this should almost create no load on the indexer and on the DB.

TestNet indexer does not seem to crash. MainNet indexer does.

## Setup

* algorand-indexer version:
  ```bash
  $ algorand-indexer -v
  2.5.0 compiled at 2021-06-22T18:26:33+0000 from git hash 1f3fb466681dc0f025be504576e4632b83130e27 (modified)
  ```
* OS: macOS BigSur 11.4

Version 2.3.4 of indexer did not have this issue.

## Urgency/Relative Priority

Relatively urgent: Allows crashes of the indexer with very low load

**Comment by winder** [comment] 2021-06-28 13:36
Duplicate of #517

**Comment by fabrice102** [comment] 2021-06-28 14:56
Two guesses (not tested/verified):
* https://github.com/algorand/indexer/blob/8a73e917dc11f963b6c1ea52cce991d37e3c3190/idb/postgres/postgres.go#L1609
does not commit/rollback the transactions.
* https://github.com/algorand/indexer/blob/8a73e917dc11f963b6c1ea52cce991d37e3c3190/idb/postgres/postgres.go#L1722 does not `.Close` the `rows` object when it early finishes the for loop (https://golang.org/pkg/database/sql/#Rows.Close)

**Comment by tolikzinovyev** [comment] 2021-06-28 16:27
@fabrice102, thanks for the suggestions! Please check if #554 fixes it.

**Closed** 2021-07-29 18:27 UTC
Labels: Team Carbon-11
