### ISSUE TITLE
Indexer does not roll back postgres TXN when rewind op hits "rewinding past txn type appl is not currently supported"

### ISSUE THREAD

**Issue by urtho** [algorand/indexer#879] opened 2022-02-12 21:32 UTC
### Subject of the issue

When indexer 2.8.3 is hit with a /v2/account request with round parameter that rewinds past unsupported TXN type it leaves a dead postgres connection. When this happens repeatedly it depletes the postgres pool and indexer starts returning 500/503. 

### Your environment

Linux, algorand-indexer 2.8.3

### Steps to reproduce

1. start indexer: `./algorand-indexer daemon --no-algod`
2. make a rewind request: `curl http://localhost:8877/v2/accounts/OUCQI775QVAIZ72LWBQY3VRN4I3XLK3ZPXWUWSQ36RIUHXLA2YRDTZYMY4?round=19201675`

### Expected behaviour

* Error message `rewinding past txn type appl is not currently supported` 
* all postgres connections in `idle` state.
* algorand-indexer process is killable with SIGTERM.

### Actual behaviour

* Error message `rewinding past txn type appl is not currently supported` 
* one connection stuck in `idle in transaction` state
* algorand-indexer process does not quit after SIGTERM

**Comment by urtho** [comment] 2022-02-12 22:02
IMHO AccountAtRound should drain txns channel before returning.

**Comment by urtho** [comment] 2022-02-12 22:28
same with fetchTransactions,

**Comment by urtho** [comment] 2022-02-14 18:12
This seems to solve the problem. 

```
diff --git a/accounting/rewind.go b/accounting/rewind.go
index 82dabb1..8a38c21 100644
--- a/accounting/rewind.go
+++ b/accounting/rewind.go
@@ -100,6 +100,13 @@ func AccountAtRound(ctx context.Context, account models.Account, round uint64, d
                MaxRound: account.Round,
        }
        txns, r := db.Transactions(ctx, tf)
+
+       defer func() {
+               // make sure txns is fully drained
+               for range txns {
+               }
+       }()
+
        if r < account.Round {
                err = ConsistencyError{fmt.Sprintf("queried round r: %d < account.Round: %d", r, account.Round)}
                return
```

**Comment by urtho** [comment] 2022-02-15 12:59
Draining can take a loooooooot of time. 
Maybe yieldTxnsThreadSimple should just be context aware and rollback when ctx is disposed/times-out.

**Comment by urtho** [comment] 2022-02-16 00:01
Am running the context aware yieldTxnsThreadSimple in production on algonode.cloud and it solves all problems. No more hanging postgres connections and no performance penalties.

**Comment by winder** [comment] 2022-02-23 01:45
@urtho thanks for the detailed report, I was able to reproduce the issue.

What was your solution for making yieldTxnsThreadSimple context-aware? In theory, it already is, because `pgx.Rows` was created with the context. This is the solution I came up with, which seems to work:
```diff
func AccountAtRound(ctx context.Context, account models.Account, round uint64, db idb.IndexerDb) (acct models.Account, err error) {
    ...
+       ctx, cf := context.WithCancel(ctx)
        txns, r := db.Transactions(ctx, tf)
+       defer func() {
+               cf()
+               for range txns {
+               }
+       }()
    ... 
```

**Comment by urtho** [comment] 2022-02-23 07:27
My tests showed that with ctx already expired the rows are coming nonetheless and it takes a lot of time to drain the channel in defer. This was apparent only for queries with a large result set that would take several seconds to read and parse. 

Have not tried to wrap the deadline ctx with cancel ctx. Not sure why this would work better with the parent ctx already Done().
Will give it a try :)

Since the code is stuck on channel send my solution that is running in production on AlgoNode is as follows:

```
diff --git a/idb/postgres/postgres.go b/idb/postgres/postgres.go
index b59c6b8..aac4079 100644
--- a/idb/postgres/postgres.go
+++ b/idb/postgres/postgres.go
@@ -617,7 +617,7 @@ func (db *IndexerDb) GetBlock(ctx context.Context, round uint64, options idb.Get
                }

                go func() {
-                       db.yieldTxnsThreadSimple(rows, out, nil, nil)
+                       db.yieldTxnsThreadSimple(ctx, rows, out, nil, nil)
                        close(out)
                }()

@@ -844,7 +844,7 @@ func (db *IndexerDb) yieldTxns(ctx context.Context, tx pgx.Tx, tf idb.Transactio
                return
        }

-       db.yieldTxnsThreadSimple(rows, out, nil, nil)
+       db.yieldTxnsThreadSimple(ctx, rows, out, nil, nil)
 }

 // Transactions is part of idb.IndexerDB
@@ -915,7 +915,7 @@ func (db *IndexerDb) txnsWithNext(ctx context.Context, tx pgx.Tx, tf idb.Transac
        }

        count := 0
-       db.yieldTxnsThreadSimple(rows, out, &count, &err)
+       db.yieldTxnsThreadSimple(ctx, rows, out, &count, &err)
        if err != nil {
                return
        }
@@ -959,10 +959,10 @@ func (db *IndexerDb) txnsWithNext(ctx context.Context, tx pgx.Tx, tf idb.Transac
                out <- idb.TxnRow{Error: err}
                return
        }
-       db.yieldTxnsThreadSimple(rows, out, nil, nil)
+       db.yieldTxnsThreadSimple(ctx, rows, out, nil, nil)
 }

-func (db *IndexerDb) yieldTxnsThreadSimple(rows pgx.Rows, results chan<- idb.TxnRow, countp *int, errp *error) {
+func (db *IndexerDb) yieldTxnsThreadSimple(ctx context.Context, rows pgx.Rows, results chan<- idb.TxnRow, countp *int, errp *error) {
        defer rows.Close()

        count := 0
@@ -1008,7 +1008,11 @@ func (db *IndexerDb) yieldTxnsThreadSimple(rows pgx.Rows, results chan<- idb.Txn
                                }
                        }
                }
-               results <- row
+               select {
+               case <-ctx.Done():
+                       goto finish
+               case results <- row:
+               }
                if row.Error != nil {
                        if errp != nil {
                                *errp = err
@@ -1018,7 +1022,12 @@ func (db *IndexerDb) yieldTxnsThreadSimple(rows pgx.Rows, results chan<- idb.Txn
                count++
        }
        if err := rows.Err(); err != nil {
-               results <- idb.TxnRow{Error: err}
+               select {
+               case <-ctx.Done():
+                       goto finish
+               case results <- idb.TxnRow{Error: err}:
+               }
+
:
@@ -617,7 +617,7 @@ func (db *IndexerDb) GetBlock(ctx context.Context, round uint64, options idb.Get
                }

                go func() {
-                       db.yieldTxnsThreadSimple(rows, out, nil, nil)
+                       db.yieldTxnsThreadSimple(ctx, rows, out, nil, nil)
                        close(out)
                }()

@@ -844,7 +844,7 @@ func (db *IndexerDb) yieldTxns(ctx context.Context, tx pgx.Tx, tf idb.Transactio
                return
        }

-       db.yieldTxnsThreadSimple(rows, out, nil, nil)
+       db.yieldTxnsThreadSimple(ctx, rows, out, nil, nil)
 }

 // Transactions is part of idb.IndexerDB
@@ -915,7 +915,7 @@ func (db *IndexerDb) txnsWithNext(ctx context.Context, tx pgx.Tx, tf idb.Transac
        }

        count := 0
-       db.yieldTxnsThreadSimple(rows, out, &count, &err)
+       db.yieldTxnsThreadSimple(ctx, rows, out, &count, &err)
        if err != nil {
                return
        }
@@ -959,10 +959,10 @@ func (db *IndexerDb) txnsWithNext(ctx context.Context, tx pgx.Tx, tf idb.Transac
                out <- idb.TxnRow{Error: err}
                return
        }
-       db.yieldTxnsThreadSimple(rows, out, nil, nil)
+       db.yieldTxnsThreadSimple(ctx, rows, out, nil, nil)
 }

-func (db *IndexerDb) yieldTxnsThreadSimple(rows pgx.Rows, results chan<- idb.TxnRow, countp *int, errp *error) {
+func (db *IndexerDb) yieldTxnsThreadSimple(ctx context.Context, rows pgx.Rows, results chan<- idb.TxnRow, countp *int, errp *error) {
        defer rows.Close()

        count := 0
@@ -1008,7 +1008,11 @@ func (db *IndexerDb) yieldTxnsThreadSimple(rows pgx.Rows, results chan<- idb.Txn
                                }
                        }
                }
-               results <- row
+               select {
+               case <-ctx.Done():
+                       goto finish
+               case results <- row:
+               }
                if row.Error != nil {
                        if errp != nil {
                                *errp = err
@@ -1018,7 +1022,12 @@ func (db *IndexerDb) yieldTxnsThreadSimple(rows pgx.Rows, results chan<- idb.Txn
                count++
        }
        if err := rows.Err(); err != nil {
-               results <- idb.TxnRow{Error: err}
+               select {
+               case <-ctx.Done():
+                       goto finish
+               case results <- idb.TxnRow{Error: err}:
+               }
+
                if errp != nil {
                        *errp = err
                }
```

**Comment by urtho** [comment] 2022-02-23 07:47
Yeah, now I get it. Morning coffee makes things so much clearer :)
You solution is much more elegant than my. 

Will confirm in a minute but it seems that this is the way to go.

**Comment by urtho** [comment] 2022-02-23 08:10
Confirmed. Your solution works perfectly, no extra lag for large resultset, no idle transactions.

**Comment by winder** [comment] 2022-03-29 20:38
This is fixed now, closing.

**Closed by winder** 2022-03-29 20:38 UTC
Labels: new-bug
