### ISSUE TITLE
Implement getting last n rounds or last n transactions.

### ISSUE THREAD

**Issue by Blackglade** [algorand/indexer#473] opened 2021-04-28 19:51 UTC
## Summary
Currently the Indexer doesn't expose any REST endpoint to enable most recent transactions / rounds.

## Scope/Requirements
As a user, I may want to get data from the last n rows (transactions/rounds) and aggregate them. Currently the only way to do is get the latest round and sequentially call `latest round - n` to find the last n rows to query data from. There should be an easier way to do this.

Current workaround is just directly querying the DB.

## Urgency/Relative Priority
Medium

**Comment by pbennett** [comment] 2021-04-28 22:50
Agreed, this is a surprising oversight.  All you can do is define ranges of rounds to walk back in time, but you have no idea of how far back to go, so you could be iteratively walking 'backwards' hundreds of blocks at a time for millions of rounds to find the last transaction for an account, asset, etc.

This is pretty foundational for applications needing to determine if there's new activity for an account since their last check or to display the last X transactions.  These operations should basically be near-instant yet the existing implementation seems to be based more for extraction from the beginning, which doesn't reflect the majority of use-cases.  An ordering clause would handle this.

**Comment by brianolson** [comment] 2021-04-29 19:43
If you want all the txns for a round, why talk to Indexer?  Any `algod` has the last 1000 rounds in local storage.

**Comment by Blackglade** [comment] 2021-04-30 02:00
Sure, but regardless of whether a someone is using Indexer/Algod, there is no REST endpoint exposed for getting the last n transactions or the last n rounds. As a developer, if I want to get the last n rounds, I'd have to do the following:

- Call /v2/status to get the current round.
- Call /v2/blocks/{round} sequentially for `current round - 1` => `current_round - n` to get get info about the last n rounds.

Then because any round can have any amount of transactions, I have to go do:

- Iterate through some n rounds to aggregate m transactions.

This is an extremely common use case. There should already be a REST api that I can simply call like this:

- /getLatestRounds/{numOfRounds}
- /getLatestTransactions/{numOfTransactions}

Whether this is done in algod / indexer / something else I have no real preferense for.

**Comment by winder** [comment] 2021-04-30 08:05
This is a duplicate of #389

**Comment by brianolson** [comment] 2021-04-30 16:47
@Blackglade what do you do with the txns once you get them? Do a web page display of the most recent N txns?

**Comment by Blackglade** [comment] 2021-04-30 17:47
@winder Yeah so part of this request is definitely a duplicate of #389. The `/transactions` endpoint exist but offers no sorting in terms of by round or timestamp from most recent => oldest. The ask is to also implement this same sort of functionality in a `/rounds` endpoint as well.

@brianolson My specific use case involves building an application that is taking recent chain data and developing metrics around this onto a webpage. That being said however, outside the scope of my particular use case, this sort of functionality would be very helpful for the larger community. Having easy access to recent chain data via blocks/transactions are useful in a variety of different applications.

**Comment by pbennett** [comment] 2021-05-05 03:30
I've got an application that monitors numerous wallets and I want to pull the latest transaction for each wallet with a single call - getting things like a note on the transaction for eg.  
This should be almost instantaneous with the indexer, and a simple call for it to handle.
/v2/accounts/xxx/transactions?limit=1 should give me the most recent transaction.  It's kind of stunning to me it doesn't work this way to be honest.

**Comment by winder** [comment] 2021-05-05 13:51
@pbennett there seems to be a miscommunication somewhere, your expectation is exactly how `/v2/accounts/xxx/transactions?limit=1` works.

**Comment by pbennett** [comment] 2021-05-05 14:12
Interesting.  The last time I looked, ordering was ascending, not descending.  You have to literally 'walk' backwards by changing round ranges.  Perhaps this is with other search criteria, but that behavior still shouldn't change.  Ordering shouldn't change based on what you do or don't search on.  If different ordering is desired, it should be its own parameter.

**Comment by brianolson** [comment] 2021-05-05 14:41
Sorry, we've designed it so that ordering _is_ different depending on what the search parameters are. Search with an accout address and you get descending order by time (the most recent txn for an account going back into the past); other searches are ascending in time. This was a guess at reasonable defaults based on usage for these two major categories of queries. And we don't allow other sort orders because these sorts align with SQL indexes, these queries should be fast and efficient. The API tries to the most common things in a good way. There's always the SQL backend for arbitrary queries.

**Comment by kirse** [comment] 2021-12-16 06:38
> Search with an accout [sic] address and you get descending order by time (the most recent txn for an account going back into the past)

What was the use-case reasoning behind this?  Blockchain is a digital ledger system where the verified audit/settling of any account starts from Tx 0 -> Tx N (latest).  Having to process a digital ledger backwards is exceptionally challenging for all sorts of reasons, many of which are due to the inherent complexities of figuring out true state + the fact that the Indexer's "next-token" pagination system splits block transactions across pages.

In the case of polling actively for latest Txs, the "newest first" approach means rather than simply store a "last processed" TxId or blockId (as in an "oldest first" approach), the pagination system means you now have to figure out if the recent page you just retrieved from the Indexer actually covers whatever you've processed up to a given point.  Throw in the need for resume/restart on an application and now you've got a challenging state management problem.

Oldest first solves all of that and is the natural order of how ledger systems work.  You don't balance a checking account from what the total currently displays (which could be wrong) and then work backward, you start at zero and accumulate in an ascending order.

**Comment by brianolson** [comment] 2021-12-16 12:07
The primary application envisioned when querying the transactions on an account is the wallet behavior, "what are my recent transactions?"

**Comment by winder** [comment] 2022-01-10 16:42
Related to #389

**Comment by algoanne** [comment] 2022-01-20 14:42
closing in favor of #389.

**Closed by algoanne** 2022-01-20 14:42 UTC
Labels: external contribution, Team Carbon-11, Usability/UX
