### ISSUE TITLE
Inconsistency between algod and indexer API result  

### ISSUE THREAD

**Issue by rotemh** [algorand/indexer#597] opened 2021-07-27 14:17 UTC
### Subject of the issue

it seems like algod removes empty values and indxer doesn't. 

### Steps to reproduce

https://indexer-mainnet/v2/assets/278022289
```
{
"asset":{
"created-at-round": 15042440,
"deleted": false,
"index": 278022289,
"params":{
"clawback": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY5HFKQ",
"creator": "JADXUXWQ5CWU2G2TTBMY7NCWGDHO3SLY7IPYVC37GTFARAZ2N5LBLWAP5A",
"decimals": 0,
"default-frozen": false,
"freeze": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY5HFKQ",
"manager": "JADXUXWQ5CWU2G2TTBMY7NCWGDHO3SLY7IPYVC37GTFARAZ2N5LBLWAP5A",
"metadata-hash": "RUFEREU0NTVBOUNBQjBGRUU2NzBEREI2MDNBQjUyNDg=",
"name": "Mask #7",
"reserve": "JADXUXWQ5CWU2G2TTBMY7NCWGDHO3SLY7IPYVC37GTFARAZ2N5LBLWAP5A",
"total": 17,
"unit-name": "MTMASK7",
"url": "https://bit.ly/3xLUSV0"
}
},
"current-round": 15252300
}
```

VS 

https://node-mainnet/v2/assets/278022289
```
{
"index": 278022289,
"params":{
"creator": "JADXUXWQ5CWU2G2TTBMY7NCWGDHO3SLY7IPYVC37GTFARAZ2N5LBLWAP5A",
"decimals": 0,
"default-frozen": false,
"manager": "JADXUXWQ5CWU2G2TTBMY7NCWGDHO3SLY7IPYVC37GTFARAZ2N5LBLWAP5A",
"metadata-hash": "RUFEREU0NTVBOUNBQjBGRUU2NzBEREI2MDNBQjUyNDg=",
"name": "Mask #7",
"reserve": "JADXUXWQ5CWU2G2TTBMY7NCWGDHO3SLY7IPYVC37GTFARAZ2N5LBLWAP5A",
"total": 17,
"unit-name": "MTMASK7",
"url": "https://bit.ly/3xLUSV0"
}
}
```

### Expected behaviour
I'd expect indexer to return empty values just when they have a meaning.

### Actual behaviour
Indexer returns the 0 byte address here when the user probably didn't set it at all. 

### Acceptance criteria: 
The following params (clawback, freeze, reserve) should not be returned if empty.
These params are currently optional.

**Comment by chaihoang** [comment] 2022-08-04 14:16
Duplicate of #939

**Closed by chaihoang** 2022-08-04 14:16 UTC
Labels: new-bug, Team Lamprey
