### ISSUE TITLE
Search by the tx amount or note prefix takes too long

### ISSUE THREAD

**Issue by scholtz** [algorand/indexer#662] opened 2021-09-18 10:07 UTC
### Subject of the issue

I am trying to search all transactions by the specific tx amount or the note prefix.

### Your environment

mainnet, testnet, sandbox

search by amount or note field prefix is required for standards [AMS-0001](https://scholtz.github.io/AMS/AMS-0001/AMS-0001.html) and [AMS-0002](https://scholtz.github.io/AMS/AMS-0002/AMS-0002.html)

Implemented for exmple in https://algo-donate.vercel.app/

### Steps to reproduce

1. Use case 1 - with minround: Go to https://algoexplorerapi.io/idx2/v2/transactions?currency-greater-than=799&currency-less-than=801&min-round=16249384&note-prefix=ZG9uYXRpb24vdjE%3D
2. Use case 2 - without minround: Go to https://algoexplorerapi.io/idx2/v2/transactions?currency-greater-than=799&currency-less-than=801&note-prefix=ZG9uYXRpb24vdjE%3D 

### Expected behaviour

Use case 1: load data within 50 ms
Use case 2: load data within 100 ms

### Actual behaviour

Use case 1: Data loaded in 5000 ms
Use case 2: Error 524 - A timeout occurred

**Comment by winder** [comment] 2022-01-10 16:25
Duplicate of #358

**Closed by winder** 2022-01-10 16:25 UTC
Labels: new-bug
